### ISSUE TITLE
Volume Editor Issues

### ISSUE THREAD

**Issue by footsoldier** [vanruesc/rabbit-hole#26]
Hi Raoul,

I'm having some issues with the volume editor code.  I've been able to solve a couple errors but don't seem to be making much progress so I wanted to reach out.  

I'm looking at public/editor/index.js.

Currently, the volume editor linked in the readme does not work for me.  It throws some 404 errors.  I pulled down the repo and fixed these errors by copying the terrain and textures folders from public/demo to public/editor.

Then, I got an error that "setOrbit was not a function".  I fixed this by commenting out line [11801](https://github.com/vanruesc/rabbit-hole/blob/master/public/editor/index.js#L11801).

Then, I got an error "TypeError: Cannot read property 'length' of undefined" which comes from line [9814](https://github.com/vanruesc/rabbit-hole/blob/master/public/editor/index.js#L9814) 

I'm afraid I'm missing a file or library or else I wouldn't keep getting errors.  Thank you for your help.

I'm using Chrome OS Version 74.0.3729.125 (Official Build) (64-bit).

By the way, the Demo project worked perfectly.

**Comment by vanruesc** [comment]
Hi,

the volume editor is currently broken. The main issue is that this library isn't complete yet. There are quite a few things I'd like to change and add, but I don't have the time and resources to commit myself to this project right now. I will continue working on this library at some point, but I don't know when that will be.

**Comment by footsoldier** [comment]
No worries, thanks for the reply.  The demo should get me headed in the right direction.  Awesome work, by the way.
